name = "laserstream-cf-rust"
main = "src/index.ts"
compatibility_date = "2026-01-08"

[vars]
LASERSTREAM_ENDPOINT = "https://laserstream-devnet-ewr.helius-rpc.com"

[[durable_objects.bindings]]
name = "LASER"
class_name = "LaserContainer"

[[migrations]]
tag = "v1"
new_classes = ["LaserContainer"]


